### ISSUE TITLE
Errot pada saat melakukan Register to access developer options.

### ISSUE THREAD

**Issue by riorin** [projectkiri/Tirtayasa#21]
Terdafat errot pada saat melakukan Register to access developer options.

`A PHP Error was encountered
Severity: Warning

Message: include_once(application/libraries/ext/PHPMailer/PHPMailerAutoload.php): failed to open stream: No such file or directory

Filename: models/PHPMailer_model.php

Line Number: 12

Backtrace:

File: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/application/models/PHPMailer_model.php
Line: 12
Function: _error_handler

File: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/application/models/PHPMailer_model.php
Line: 12
Function: include_once

File: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/application/controllers/Dev.php
Line: 110
Function: model

File: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: include_once(): Failed opening 'application/libraries/ext/PHPMailer/PHPMailerAutoload.php' for inclusion (include_path='.:/usr/share/php')

Filename: models/PHPMailer_model.php

Line Number: 12

Backtrace:

File: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/application/models/PHPMailer_model.php
Line: 12
Function: _error_handler

File: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/application/models/PHPMailer_model.php
Line: 12
Function: include_once

File: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/application/controllers/Dev.php
Line: 110
Function: model

File: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/index.php
Line: 315
Function: require_once

An uncaught Exception was encountered
Type: Error

Message: Class 'PHPMailer' not found

Filename: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/application/models/PHPMailer_model.php

Line Number: 16

Backtrace:

File: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/application/controllers/Dev.php
Line: 110
Function: model

File: /home/pndevworks_deploy/projectkiri/Tirtayasa/www/index.php
Line: 315
Function: require_once`

**Comment by pascalalfadian** [comment]
Ah ya, terima kasih laporannya. Sepertinya terlewat sama saya untuk konfigurasi composer nya. Nanti diperbaiki dulu ya.

**Comment by pascalalfadian** [comment]
Saat ini sudah dilakukan beberapa perbaikan, yaitu dengan:

* update git module PHPMailer
* set base url (b48bf0ae4c4ececd5136dc72f291afa8243a4ed6)

Tetapi masih bermasalah di koneksi ke SMTP. Kemungkinan akan diganti, tidak lagi menggunakan PHPMailer menggunakan milik CodeIgniter saja.

**Comment by riorin** [comment]
Terimakasih, Ditunggu perbaikannya pak

**Comment by pascalalfadian** [comment]
Hi @riorin mohon dicoba lagi ya, sudah fixed di 78a952475415f3ada90df5a63f6e6252d052f706
