### ISSUE TITLE
Google API issues

### ISSUE THREAD

**Issue by pascalalfadian** [projectkiri/Tirtayasa#22]
There are several issues regarding to Google API here. First, screenshots...

![screen shot 2018-10-03 at 17 18 59](https://user-images.githubusercontent.com/5976057/46446778-78356b00-c7a8-11e8-8959-44e53bb044ef.png)
![screen shot 2018-10-03 at 17 19 23](https://user-images.githubusercontent.com/5976057/46446780-78356b00-c7a8-11e8-9b5b-d58a906472aa.png)
![screen shot 2018-10-03 at 17 19 27](https://user-images.githubusercontent.com/5976057/46446782-78ce0180-c7a8-11e8-8c85-2ad0cbd49efb.png)

Due to server change to Linode, all the geocoding and place search caches were cleared, and causes sudden spike in Google API usage, more than $200 free credit from Google. It happened also that Google API charged to my old credit card account that does not exist yet. Therefore, two things are needed:

* [x] Switch to a proper credit card
* Also I noticed that I am using two premiums that are actually not needed, hence need to be disabled, simply by explicitly says in the request what I want only:
    - [x] Places API Contact Data
    - [x] Places API Atmosphere Data

**Comment by TommyAdhityaThe** [comment]
Oke Pak

**Comment by TommyAdhityaThe** [comment]
Wah maap Pak, salah sangka saya hahaha
