### ISSUE TITLE
Confirmation email sending error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by GoLok56** [projectkiri/Tirtayasa#23]
Maaf mas mba, saya mau coba-coba pakai API Kiri .. Tapi kenapa ya saat saya coba untuk daftar API Key nya selalu mendapatkan error? Mohon bantuannya mas, terimakasih..

**Comment by pascalalfadian** [comment]
Iya mohon maaf ya, masih dalam perbaikan. Kami usahakan secepatnya, target minggu ini.

Related to #21

**Comment by GoLok56** [comment]
oh iya mas, maaf saya juga. Saya ga melihat issue yang lain dulu padahal udah ada yang buka. Yang ini bisa diclose aja mas. Oh iya tapi sebelumnya mau minta konfirmasi, perkiraan paling cepat untuk minggu ini apa bisa mencapai tanggal 11?

**Comment by pascalalfadian** [comment]
bisa dicoba lagi? sudah fixed harusnya di #21. Kalau boleh tahu, ini untuk tugas? Soalnya tidak biasanya ada yang pakai API ini (tentu saja saya senang)

**Comment by GoLok56** [comment]
Oh iya sudah bisa mas, terimakasih mas. Rencananya saya mau coba-coba dulu, kalau emang cocok dan ide saya disetujui dosen, saya mau pake untuk tugas besar rpl saya mas. Untuk bikin chatbot yang memberikan informasi angkot2 Bandung.

**Comment by pascalalfadian** [comment]
Wow mantap! Good luck ya.
Sama sama.

On 10 Oct 2018, at 09.49, Satria Adi Putra <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh iya sudah bisa mas, terimakasih mas. Rencananya saya mau coba-coba dulu, kalau emang cocok dan ide saya disetujui dosen, saya mau pake untuk tugas besar rpl saya mas. Untuk bikin chatbot yang memberikan informasi angkot2 Bandung.
