### ISSUE TITLE
Why did i got CONNECTION PROBLEM alert ?

### ISSUE THREAD

**Issue by gagantous** [projectkiri/Tirtayasa#25]
I always got this message

![test](https://user-images.githubusercontent.com/24579576/47610929-a5b5c180-da93-11e8-85e6-3e9e756f0f5b.PNG)
Does my connection that went wrong ? or is there a problem with kiri travel server ? 
thanks in advanced

**Comment by pascalalfadian** [comment]
You’re right, I’m sorry. It happens here, too. Will check it once I get access to my laptop.

**Comment by pascalalfadian** [comment]
Can you try again? Seems due to memory problem. Restarted the server and it’s fine. Will upgrade if it happens again. Please reopen the issue in such case. Thanks.

**Comment by gagantous** [comment]
Hi @pascalalfadian 
I think the server down again, since i got "Connection Problem" message again...

**Comment by pascalalfadian** [comment]
Thanks for notifying. Different problem compared to before. Not sure yet why, but a restart of the daemon fixed it. Please try again.

**Comment by gagantous** [comment]
thanks for fixing it!
