### ISSUE TITLE
Color change of Margahayu-Ledeng route

### ISSUE THREAD

**Issue by notrhnk** [projectkiri/Tirtayasa#36]
Hello!
First of all, I want to thank you to the point I can even bow to the team who made this project. As the price of online drivers now is increasing, this project helps me a lot for dozens of times. It's super useful, so I hope you keep maintaining the web.

But I have this one issue about the color of Margahayu-Ledeng track. It has purple color on the web, but apparently it has the color of blue and yellow. Idk if it changed or it's just some code error on the web but I hope you fix it since I missed so much time today because I was looking for purple one.

Thanks!

**Comment by pascalalfadian** [comment]
Hi @notrhnk

Thank you for your kind words. I am now keeping the website alive but in low maintenance mode in terms of no new features added. However, I can do bugfixes like this if the implementation does not require major work.

As for the issue itself, can you help me to give example of "from" and "to" that makes the problem appear? Screenshot would be helpful as well. I tried a simple query from "RSIA Limijati" to "RS ZR Tedja" and it shows blue-yellow in my screen: 
[Screenshot from 2021-06-04 11-35-23](https://user-images.githubusercontent.com/5976057/120746990-7b212480-c52a-11eb-9a6a-0facddadb900.png)

Best regards;  
Pascal

**Comment by notrhnk** [comment]
Ah, I see now. Mine was the same color with the one that you attached, but I thought it was purple. It's kind of confusing though, since the real color is not close at all to purple but the one that appears on web is a purple-ish blue. Maybe you can change it similar to the real one?

Thank you.
![images (21)](https://user-images.githubusercontent.com/85325971/120804259-a3cb0d80-c56e-11eb-83a7-7346115b9091.jpeg)

**Comment by pascalalfadian** [comment]
How about this?

![margahayuledeng](https://user-images.githubusercontent.com/5976057/120885893-7edda580-c615-11eb-835e-2cedbc3e2a30.png) ![margahayuledeng](https://user-images.githubusercontent.com/5976057/120885897-82712c80-c615-11eb-9fec-1688700641c9.png)

**Comment by notrhnk** [comment]
In the bigger size, that looks okay but I'm afraid I mistake it as green once it's applied smaller. Especially when you have a blue bubble chat 💭 that affects the car to look more like it's green rather than blue.

Sounds trivial, but since some people only take a quick glance, I think it's better to use colors that aren't difficult to distinguish (blue that everyone sees as blue, not purplish or greenish one).

Maybe you can take it for future consideration 😊 If it's not possible now because of the coding or stuff, I hope you find a way soon!

Put this issue aside, the project itself is awesome!
Thanks!

**Comment by pascalalfadian** [comment]
Noted. Thanks for your feedback and I am sorry for the confusion. The images are small because at the time I started this project, most screens are in low resolution. Will think of enlarging the image in the future. For now, I just change the color to make it a little bit more accurate.

Thanks again, and I wish you safe travel using angkot.
