### ISSUE TITLE
Link Temanbus pada peta selalu mengarah ke https://projectkiri.id

### ISSUE THREAD

**Issue by YudithDwiHardyanto** [projectkiri/Tirtayasa#37]
Hai @pascalalfadian 

Steps
1. Setup proyek ke lokal
2. Buka http://localhost/index.php/temanbus di address bar browser lokal anda
3. Cari Taman Radio, lalu arahkan cursor dan klik Taman Radio
4. Mengarah ke link https://projectkiri.id/temanbus/threesixty/Taman-Radio

Expected result
https://localhost/temanbus/threesixty/Taman-Radio

Actual result 
https://projectkiri.id/temanbus/threesixty/Taman-Radio

**Comment by pascalalfadian** [comment]
Link tersebut dibangun pada view [`main.php`](https://github.com/projectkiri/Tirtayasa/blob/temanbus/httpdocs/application/views/temanbus/main.php#L32) menggunakan [`site_url()`](https://codeigniter.com/userguide3/helpers/url_helper.html?highlight=site_url#site_url), di mana nilainya diambil dari [`config.php`](https://github.com/projectkiri/Tirtayasa/blob/temanbus/httpdocs/application/config/config-dev.php#L26). Mohon dicek apakah di `config.php` sudah mengarah ke http://localhost ?

**Comment by YudithDwiHardyanto** [comment]
Sudah saya coba ubah pada config.php menjadi http://localhost namun keluarannya berupa 404 Page Not Found

**Comment by pascalalfadian** [comment]
Bisa dijelaskan, Page Not Found saat melakukan apa, dan URL lengkap 404 nya apa?

**Comment by YudithDwiHardyanto** [comment]
Mengganti `$config['base_url'] = 'http://projectkiri.id'; `menjadi `$config['base_url'] = 'http://localhost';` pada `config.php,` url lengkap 404 http://localhost/images/temanbus/360/Taman-Radio

**Comment by YudithDwiHardyanto** [comment]
Ingin konfirmasi terhadap issue ini ternyata saat dicoba pada komputer rekan saya berhasil hanya bermasalah dikomputer saya, Terimakasih atas feedbacknya, apakah saya perlu untuk menutup issue ini?

**Comment by pascalalfadian** [comment]
Ya. Karena bukan bug pada KIRI, saya tutup issue nya.
